spring:
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:cakeBakerDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
